### ISSUE TITLE
Setting the refresh rates for a secondary monitor

### ISSUE THREAD

**Issue by dejavecue** [kevinlekiller/mpv_scripts#12]
For now I am using nircmdc.exe manually to change my secondary monitor's refresh rate to either 48, 50 or 60 Hz depending on the framerate of the video file. 
Somehow, autospeedwin.lua, despite changing the config file according to my needs, does not affect my secondary monitor. 

Am I doing something wrong or is it a limitation of the script?

**Comment by kevinlekiller** [comment]
It's probably a limitation, I don't have access to Windows anymore, but if you figure out how to specify the monitor to nircmdc, we can try changing the script to have that option.

**Comment by dejavecue** [comment]
Well, nircmdc can be used to change any monitor like this (this is actually one of the scripts I use manually):
`nircmdc.exe setdisplay  monitor:1 3840 2160 32 48`

where monitor:1 is the number of the display (starting from 0)

I thought that if I changed line 252 accordingly 
`    ["args"] = {
            [1] = _global.options["nircmdc"],
            [2] = "setdisplay monitor:1",
            [3] = _global.options["dwidth"],
            [4] = _global.options["dheight"],
            [5] = _global.options["bdepth"],
            [6] = rate`
that this might do the trick, but it does not work

**Comment by kevinlekiller** [comment]
Thanks, will add an option to use "monitor".

**Comment by kevinlekiller** [comment]
Should be good now.

**Comment by dejavecue** [comment]
It works beautifully! Thank you very much for your prompt reply
