### ISSUE TITLE
Autospeed causes audio to be distorted

### ISSUE THREAD

**Issue by zaskokus** [kevinlekiller/mpv_scripts#19]
With recent versions of mpv `autospeed.lua` has started to cause weird audio issues. Sound seems to speed up and down causing sounds to change frequency and everything feels "off tune". Changing resetting playback speed with backspace, then adjusting with [ ] buttons does not cause the same issue. It has started quite recently, maybe a month ago. Currently running `mpv 1:0.34.1-1` on Arch Linux.

**Comment by kevinlekiller** [comment]
Could be related to https://github.com/mpv-player/mpv/issues/8705 ?

**Comment by zaskokus** [comment]
> Could be related to [mpv-player/mpv#8705](https://github.com/mpv-player/mpv/issues/8705) ?

I was about to edit my post and add my `mpv.conf` which in fact has scaletempo2 enforced. I'm going to see how do I undo it.
```
audio-swresample-o=matrix_encoding=dplii,lfe_mix_level=1
audio-channels=stereo
af=scaletempo2

video-sync=audio

load-scripts=yes
script-opts=autospeed-xrandr=false,autospeed-speed=true,autospeed-display=auto,autospeed-exitmode=auto,autospeed-minspeed=0.87,autospeed-maxspeed=1.13,autospeed-osd=true,autospeed-osdtime=10,autospeed-osdkey=y,autospeed-estfps=true,autospeed-spause=4
```

**Comment by zaskokus** [comment]
Switching `scaletempo2` to `scaletempo` has solved the issue. That was quick. Thanks!

**Comment by zaskokus** [comment]
@kevinlekiller 
The interesting bit being that it only happens with speeds set by `autospeed.lua`. Once reverted by backspace, then set with [ ] { } keys - the issue was not present - that's why I thought originally the `autospeed.lua` was at fault.

**Comment by kevinlekiller** [comment]
No worries.

I think it's because like the issue mentions, the audio only becomes messed up with small changes, while the keybinds change +/- 10%.
