### ISSUE TITLE
144Hz for 23.976/24fps videos not working for me

### ISSUE THREAD

**Issue by Quantum00** [kevinlekiller/mpv_scripts#2]
Amazing, script mate, huge thanks!
For some reason I can't get autospeed to keep desktop 144Hz for 23.976/24fps videos. Is it bug or not supported? If not supported could you please add it?

**Comment by kevinlekiller** [comment]
Thanks, which script do you use, the Windows one or the nix one?

**Comment by Quantum00** [comment]
Windows. To clarify, I have refresh rates set to 100,120,144 for (i'd want the plugin to use 100hz for 25 and 50fps videos, 120hz for 30 and 60 fps videos and 144hz for 24fps). My desktop is set to 144Hz. It should keep 144Hz for 23.976/24fps videos. but currently it switches to 120hz. (I haven't tested with 25 and 50 fps videos yet)

**Comment by Quantum00** [comment]
Sorry, incorrectly clicked "close and comment" instead of "comment" before.

**Comment by kevinlekiller** [comment]
No problem, looking into the issue currently.

**Comment by kevinlekiller** [comment]
Alright I found the issue, basically the loop goes through all the rates (100, 120, 144), then it returns the rate which is the closest divisible by the video fps, in the case of 24, it's perfectly divisible by 120 and 144, so it returns 120 since the loop stops on it first.

I'll add an option to continue the loop even if it already found a perfectly divisible rate for the video.

**Comment by kevinlekiller** [comment]
Actually I don't have to add an option, you can change `autospeed-rates` to the inverse, for example: `autospeed-rates=144,120,100`, then 144 will be preferred over 120.

I'll add this to the documentation.

**Comment by Quantum00** [comment]
Ok, something wierd is happening. I tried many different orderings
100,120,144: 23.976fps to 120Hz (should be 144Hz),  25fps to 100Hz, 29.970 to 120Hz
100,144,120: 23.976fps to 120Hz (should be 144Hz),  25fps to 100Hz, 29.970 to 120Hz
120,100,144: 23.976fps to 120Hz (should be 144Hz),  25fps to 100Hz, 29.970 to 120Hz
120,144,100: 23.976fps to 100Hz (should be 144Hz),  25fps to 100Hz, 29.970 to 100Hz  (should be 120Hz)
144,100,120: 23.976fps to 120Hz (should be 144Hz),  25fps to 100Hz, 29.970 to 120Hz
144,120,100: 23.976fps to 100Hz (should be 144Hz),  25fps to 100Hz, 29.970 to 100Hz  (should be 120Hz)

**Comment by kevinlekiller** [comment]
Weird, I don't have a 144hz monitor to test, so it was more of a assumption, possibly the rates are being re-ordered, I'll see if that happens.

Thanks.

**Comment by kevinlekiller** [comment]
I think I found an issue, not sure if it will fix your issue, let me know.

**Comment by Quantum00** [comment]
It works!
I only tested with 144,100,120. The display refresh rate doesn't change from my desktop default 144Hz when playing 23.976 and it changes correctly for the other video fps rates.
A minor thing is that a cmd window pops up for a second and then goes away when the refresh rate doesnt change. I'm guessing its nircmdc?
Maybe the script shouldnt run it at all if the target refresh rate is already set.

**Comment by kevinlekiller** [comment]
Yeah, it's nircmd, this is something I fixed on the nix version, but I don't have access to Windows anymore.

I can try to fix it on WIndows if you're willing to test.

**Comment by Quantum00** [comment]
Great work man, no cmd window now and everything is working as intented!
Huge thanks!

**Comment by kevinlekiller** [comment]
Thanks, no problem.
