### ISSUE TITLE
The video starts playing before the screen HZ changes.

### ISSUE THREAD

**Issue by JulianLai** [kevinlekiller/mpv_scripts#6]
Can the video playback starts after the screen HZ is changed.

**Comment by kevinlekiller** [comment]
Hi @JulianLai , this is what the "autospeed-spause" option is for:

https://github.com/kevinlekiller/mpv_scripts/blob/master/autospeed/autospeed.lua#L23

For example: `mpv --script-opts=autospeed-xrandr=true,autospeed-spause=3` will pause the video for 3 seconds.

**Comment by JulianLai** [comment]
Thanks!

**Comment by fighuass** [comment]
Doesn't seem to work for me, when it's set to either true or false it has the same behavior, and when I try to assign it a number it gives me the 

`[autospeed] Command subprocess: argument args has incompatible type.`

error.
