### ISSUE TITLE
Why does it change the refresh rate to 59.94hz when playing a 30fps live stream.

### ISSUE THREAD

**Issue by JulianLai** [kevinlekiller/mpv_scripts#7]
![yyyyyyy](https://cloud.githubusercontent.com/assets/20014762/21577718/d32c4112-cf9f-11e6-9081-1e0009b51704.png)
Shouldn't it stay at 60hz?

**Comment by kevinlekiller** [comment]
It will detect all the rates you have, these are iterated from smallest to largest, ideally it should detect if there's a perfect rate like in your case, but I've not had the time to do that yet.

For now you can use the blacklist option if you don't want to use the 59.94 rate: https://github.com/kevinlekiller/mpv_scripts/blob/master/autospeed/autospeed.lua#L13

For example:

    $ xrandr --verbose
    ...
      1920x1080 (0x104) 148.352MHz +HSync +VSync
            h: width  1920 start 2008 end 2052 total 2200 skew    0 clock  67.43KHz
            v: height 1080 start 1084 end 1089 total 1125           clock  59.94Hz
    ...

`mpv --script-opts=autospeed-mblacklist="0x104",autospeed-xrandr=true`

**Comment by kevinlekiller** [comment]
Let me know if this worked.

**Comment by JulianLai** [comment]
I haven't tried it, because I need 59.94hz in most cases.

**Comment by kevinlekiller** [comment]
Sorry, I meant commit 6c41b62, not the blacklist option.

**Comment by JulianLai** [comment]
@kevinlekiller It works!
