### ISSUE TITLE
There is a new problem with the "6c41b62"

### ISSUE THREAD

**Issue by JulianLai** [kevinlekiller/mpv_scripts#8]
[6c41b62](https://github.com/kevinlekiller/mpv_scripts/commit/6c41b62b0f3026b4291d021f832fa69e39a3f53f)

It plays 30fps video at 60hz without problem, but it doesn't change the refresh rate to 59.94hz when playing a 29.97fps video.

No problem with 30fps:
![30_60](https://cloud.githubusercontent.com/assets/20014762/21629962/9e848396-d267-11e6-92a2-cf5545dda803.png)

Still stays at 60hz with a 29.97fps video:
![29 9_60](https://cloud.githubusercontent.com/assets/20014762/21629980/c8311736-d267-11e6-8356-6d42c60de724.png)

**Comment by kevinlekiller** [comment]
Try using the non rounded value (`_global.temp["fps"]`), let me know if it works.

**Comment by JulianLai** [comment]
@kevinlekiller  It works! 
Should I delete `local round_fps = round(_global.temp["fps"])`?

**Comment by kevinlekiller** [comment]
No, it's needed for other calculations lower.

Will submit the change, thanks.

**Comment by kevinlekiller** [comment]
01ca1bb
