### ISSUE TITLE
The keybinding of perfstats doesn't work

### ISSUE THREAD

**Issue by JulianLai** [kevinlekiller/mpv_scripts#9]
I've pressed `, but nothing happens

**Comment by kevinlekiller** [comment]
You can change the keybinding here: https://github.com/kevinlekiller/mpv_scripts/blob/master/perfstats/perfstats.lua#L49

**Comment by kevinlekiller** [comment]
I referenced the wrong issue, sorry.

**Comment by JulianLai** [comment]
[perfstats] Lua error: /home/user/.config/mpv/scripts/perfstats.lua:84: attempt to concatenate a nil value

**Comment by kevinlekiller** [comment]
Ok, that's a different issue, the keybind works fine, it's just mpv is not able to find your display-fps for some reason.

**Comment by kevinlekiller** [comment]
I'll add more checks to see if they are nil first.

**Comment by JulianLai** [comment]
[perfstats] Got a nil value from mpv for property : mistimed-frame-count

**Comment by kevinlekiller** [comment]
Some mpv backends don't have all these properties.
